version: '3.8'

services:
  neuralink-core:
    image: neuralinktech/ai-diagnostics:4.2.0
    build: .
    privileged: true
    environment:
      - CAN_INTERFACE=can0
      - PLATFORM_TYPE=${PLATFORM_TYPE:-auto}
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/can0:/dev/can0"
    networks:
      - vehicle-net

  diagnostics-api:
    image: neuralinktech/diagnostics-api:2.1
    ports:
      - "8080:8080"
    depends_on:
      - neuralink-core
    environment:
      - CORE_SERVICE=http://neuralink-core:8000
    networks:
      - vehicle-net

networks:
  vehicle-net:
    driver: bridge